### ISSUE TITLE
CSS within HTML

### ISSUE THREAD

**Issue by Yannick-DG** [jvidalv/vital#2]
Hi there,

I'm wondering, there's atm no way to add CSS in HTML, is it possible to get that turned on/disable something to make that happen? I'm running a few queries in my CSS but somehow it is not catching the variables within .css files that I've defined in my tailwind.config.js

**Comment by jvidalv** [comment]
Hi Yannick, yes it is.

You can turn off css-modules by going to `postcss.config.file`and set modules to `false`.

Then you must go to `tailwind.config.js` and change the `purge` prop with: `purge: ["./*.html", "./src/**/*.{css,tsx}"]`. So the JIT of Tailwind also takes into account `.tsx` files.

I with these two now you should be able to write tailwind classes inline in jsx.

In any case, tell me if it doesn´t work, and also extend the explanation of your issue so I can help you more.

Cheers!

**Comment by Yannick-DG** [comment]
It's hard to explain to be fair, I'd like to use both the CSS modules, but also want to add sometimes something inline within the TSX component.

https://i.file.glass/d3eiJIkWaI.png

https://i.file.glass/L7oRSdKzWA.png

I've got this within my CSS class and the sidebarOpen and sidebarClosed don't seem to work somehow.

Now when I turned off your given values, it works but I don't want everything to be inline.

**Comment by jvidalv** [comment]
Hey Yannick, I use that approach and it works well with css-modules.

The problem is the `cx`.

Use `classnames` library instead: https://www.npmjs.com/package/classnames

Then you can do:

```jsx
import classNames from 'classnames'
//....
//....
<div className={classNames(styles.sidebar, sidebarOpen ? styles.sidebarOpen : styles.sidebarClose)}>Hello</div>
```

Now it should work as you expect.

Cheers.

**Comment by Yannick-DG** [comment]
I wrote the cx myself, this is the code I used.

```
export type ClassType = string | null | false | undefined;

function joinClassnames(...classes: ClassType[]): string {
  return classes.filter(Boolean).join(" ");
}

const cx = joinClassnames;

export default joinClassnames;
export { cx, joinClassnames };
```

I assume it's broken then?

**Comment by Yannick-DG** [comment]
Looks like that didn't work either using classnames, eventually you want to have a look over Discord or such?

**Comment by jvidalv** [comment]
Yes why not, share a link. Ill go in.

**Comment by yannickboy15** [comment]
Username is Yannick#1936

**Comment by Yannick-DG** [comment]
We've found the solution together. As the root div was another element, using the :global tag, including that specific class name will solve the issue as follows:

```
.sidebar {
  @apply [CLASSES HERE]
}

:global(.sidebar-expanded) .sidebar {
  @apply lg:!w-64;
}

```
