### ISSUE TITLE
How can I use tailwind-css in React?

### ISSUE THREAD

**Issue by brend8c** [jvidalv/vital#8]
Please help me
How can I use tailwind-css in React?
I already asked a similar question [here ](https://stackoverflow.com/questions/75587348/how-to-use-tailwind-css-with-react-and-module-scss)

**Comment by jvidalv** [comment]
Hi, not sure exactly what are you doing that is not correct, does this template not work straight out?

Try creating a fresh react repo with tailwind that it works, then try to add scss and check in which step it starts failing.

**Comment by brend8c** [comment]
@jvidalv Hi, no, my build is working.
When I use module.scss my Tailwind-CSS styles in React stop working.
Here example Header.jsx file:
```javascript
import cn from 'classnames';
import classes from '../scss/style.module.scss';

const Header = () => {
  return (
    <header className={cn(classes.header, 'flex')}>
      <img className="h-50 w-full" src="/src/assets/image-0.png" alt="image" />
    </header>
  );
};
export default Header;

```
Here we see how I include the "header" class from the style.module.scss file, styles in this file even the Tailwind-CSS classes work.
Also we see in React file that I am trying to use tailwind-css classes like: 'flex', "h-50 w-full".
These classes are displayed in index.html in the browser, but there are no styles themselves. Tailwind-CSS ignored the written classes in React and did not add its own styles to them.
Do you have any idea how this can be solved?

Tried a similar entry and it didn't work either: 
```javascript
<div className={`${classes.item}` + ' ' + `absolute`}>
<div className={`${classes.item} ${'absolute'}`}>
<div className={cn(classes.item) + ' ' + `${'absolute'}`}>
<div className='absolute'>
```
